### ISSUE TITLE
Thumbnails do not load

### ISSUE THREAD

**Issue by Falteri** [Daniel-KM/Omeka-S-module-Mirador#8]
It often happen that thumbnails do not load when loading multi-part object (e.g.: https://www.e-codices.unifr.ch/metadata/iiif/kba-MurF0008/manifest.json).

**Comment by Falteri** [comment]
I think it worth to update mirador to version 2.7.0 (latest release) as it has been emproved in loading thumbnails ("Updates to the eventedCanvas library to improve thumbnail robustness")

**Comment by Daniel-KM** [comment]
Hi,
I just published version 3.1.7 ([in releases](https://github.com/Daniel-KM/Omeka-S-module-Mirador/releases)) that includes both version 2.7.0 and version 3.0 beta, that may fix your issue. Note that you may have to set the version in the site settings.

**Comment by Falteri** [comment]
Hi Daniel,
apparently this doesn't solve the issue.
Can you clarify me what you mean with setting the version in site settings? And how I can switch from 2.7.0 to 3.0 beta?

**Comment by Falteri** [comment]
Is the v 3.0 in asset/vendor/mirador-2 folder?

**Comment by Falteri** [comment]
I've also seen that in mirador version 2.7.0 folder some subfolders seem to be missed, like images and locales. And mirador-plugin is missed too.

**Comment by Falteri** [comment]
I think you mean this part of modul config php:

        'site_settings' => [
            'mirador_version' => '2',
            'mirador_plugins' => [],
            'mirador_config_item' => null,
            'mirador_config_collection' => null,
            'mirador_preselected_items' => 0,
        ],

Right?

**Comment by Falteri** [comment]
Hi Daniel,
version 3.0 seems to solve the issue, while 2.7.0 seems not.
3.0 also works smoother and looks lighter. It seems to be the right choice even if still in Beta. Do you want me to check something? Plugins?

**Comment by Falteri** [comment]
I see that if in site settings if you choice 3.0, then the list of available plugins disappears.
I also noted that with version 2.7 selected is there someting missed while web page is loaded:

_GET http://omeka.ifnet.it/modules/Mirador/asset/vendor/mirador/locales/en-US/translation.json 404 (Not Found)
GET http://omeka.ifnet.it/modules/Mirador/asset/vendor/mirador/locales/en/translation.json 404 (Not Found)
GET http://omeka.ifnet.it/modules/Mirador/asset/vendor/mirador/images/debut_dark.png 404 (Not Found)_

I finally noted that while a mirador-2-plugin folder is present in asset/vendor, a mirador-plugin folder it is not, but I'm not sure if this is by design.

Hope this help

**Comment by Daniel-KM** [comment]
When you download a module from Github, it's preferable to use the [releases](https://github.com/Daniel-KM/Omeka-S-module-Mirador/releases), that contain all dependencies, instead of the button "Download" on the first page that contains only the source code. If you use the source code, run `composer install --no-dev && npm install && gulp` from the root of the module. 

So in the new version, Mirador 2 installed in /asset/vendor/mirador-2 and mirador-2-plugins, and Mirador 3 in /asset/vendor/mirador. There are no plugins for mirador 3 currently, they will be installed in mirador-plugins. What are the missing folders?

**Comment by Daniel-KM** [comment]
For the missing files, it seems that mirador 2 try to load ressources from the old directory.

**Comment by Daniel-KM** [comment]
Probably fixed in last version (3.1.7.3).
