### ISSUE TITLE
Mirador don't load

### ISSUE THREAD

**Issue by alfonsomontejo** [Daniel-KM/Omeka-S-module-Mirador#9]
I have a custom theme/view/omeka/site/item/show.phtml file with this code:

`<?php
if (count($lightMedia) > 0) { echo $this->mirador($item);}
    else {echo "<div style='padding-top:50px;'></div>";}
?>`

After 3.1.6 release, the helper `echo $this->mirador($item)` don't seem to work anymore. Mirador still can load with `<?php $this->trigger('view.show.after'); ?>`, but not with the helper.

Thank you first of all for your excellent work with this and many other modules for Omeka S. And sorry for my English.

**Comment by Daniel-KM** [comment]
This is probably fixed in last version (3.1.7.3).

**Comment by alfonsomontejo** [comment]
Sorry, Daniel, viewer still don't load (latest version, Mirador-3.1.7.3). Thanks for your work.

**Comment by Daniel-KM** [comment]
It should be fixed one more time for the version 3, where there are many change.

**Comment by Daniel-KM** [comment]
It should be fixed one more time for the version for Omeka 3, where there are many changes.
